### ISSUE TITLE
The step 2

### ISSUE THREAD

**Issue by yoplaitXYZ** [zinkwazi/pfmb#4]
Hello,

Thank you for your soft,

I try to install it , but I not understand the step two when you :
##### Setup your ~/.ssh/config file to pass the correct identity for your backup user:

```
Host *
User backup
IdentityFile ~/.ssh/backup-user.rsa
```

Can you help me

Thank's

**Comment by Piega** [comment]
Check this guide:
https://www.bytesizedalex.com/pfsense-ssh-key-authentication/

**Comment by zinkwazi** [comment]
Added the backup username to the script to make it easier.
